name: BanManager
version: 1.3
author: CrackLPYT
main: de.crack.lp.main.Main

commands:
  ban:
    permission: banmanager.ban
  tempban:
    permission: banmanager.tempban
  check:
    permission: banmanager.check
  unban:
    permission: banmanager.unban
  kick: